// Get all carousels
GET http://localhost:4000/api/carousel

###

// Get specific carousel
GET http://localhost:4000/api/carousel/2

###

// Add carousel
POST http://localhost:4000/api/carousel
Content-Type: application/json

{
    "name": "Carousels",
    "tickets": 1
}

###

// Update carousel
PUT http://localhost:4000/api/carousel/1
Content-Type: application/json

{
    "name": "Slugs roller",
    "tickets": "$$"
}

###

// Delete carousel
DELETE http://localhost:4000/api/carousel/"60827d583c6dcee68e35972b"