// Get all posts
GET http://localhost:4000/api/post

###

// Get specific post
GET http://localhost:4000/api/post/2

###

// Add post
POST http://localhost:4000/api/post
Content-Type: application/json

{
    "rating": 3,
    "image": "https://raw.githubusercontent.com/feliciavonbraun/rainbow-land/main/client/src/assets/carouselPics/carousel1.jpeg",
    "comment": "Superduper!",
    "carouselTag": "Roller coaster"
}

###

// Update post
PUT http://localhost:4000/api/post/608bdf30a210c3d327c91edb
Content-Type: application/json

{
    "rating": 3,
    "image": "https://raw.githubusercontent.com/feliciavonbraun/rainbow-land/main/client/src/assets/carouselPics/carousel1.jpeg",
    "comment": "YAY!"
}

###

// Delete post
DELETE http://localhost:4000/api/post/6088234442b0ba5c0a1a318c