// Get all posts
GET http://localhost:4000/api/post

###

// Get specific post
GET http://localhost:4000/api/post/2

###

// Add post
POST http://localhost:4000/api/post
Content-Type: application/json

{
    "rating": 3,
    "description": "Superduper!"
}

###

// Update post
PUT http://localhost:4000/api/post/6087c0fe926a8e395a1c1412
Content-Type: application/json

{
    "rating": 3,
    "description": "höhöhöhö!"
}

###

// Delete post
DELETE http://localhost:4000/api/post/6088234442b0ba5c0a1a318c