// Get all posts
GET http://localhost:4000/api/post

###

// Get specific post
GET http://localhost:4000/api/post/2

###

// Add post
POST http://localhost:4000/api/post
Content-Type: application/json

{
    "rating": 3,
    "description": "SuperFun!"
}

###

// Update post
PUT http://localhost:4000/api/post/60827e6d9f0600e6bcc0b498
Content-Type: application/json

{
    "username": "Slug roller",
    "rating": 3,
    "description": "My favorite!"
}

###

// Delete post
DELETE http://localhost:4000/api/post/"60827d583c6dcee68e35972b"